text_block:
  introduction:
    line_1: "You are waken up by a strange guy. You notice you are below a tree, inside a dark forest."
    line_2: "\"Hello, I'm %{stranger}. What is your name?\" - asks the guy."
  sword_pick:
    line_2: "\"So, you're a brave one, %{hero}...\" - says %{stranger}, portraying an ironic smile."